/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.KandidatDao;
import application.dao.KaryawanDao;
import application.daoimpl.KandidatDaoImpl;
import application.daoimpl.KaryawanDaoImpl;
import application.models.KandidatModel;
import application.models.KaryawanModel;
import application.utils.DatabaseUtil;
import java.io.InputStream;
import java.sql.Connection;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mhdja
 */
public class PerhitunganSawView extends javax.swing.JPanel {
    public final KaryawanDao karyawanDao;
    public final KandidatDao kandidatDao;
    private final Map<String, Integer> karyawanMap = new HashMap<>();
    
     public void getAllData() {
        List<KandidatModel> kandidatList = kandidatDao.findAll();

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "Nama Karyawan", "Productivity", "Quality", "Tanggung Jawab", 
            "Improvement", "Absensi", "Psikotest", "Hasil"
        });

        for (KandidatModel kandidat : kandidatList) {
            model.addRow(new Object[]{
                kandidat.getNameKaryawan(),
                kandidat.getProductivity(),
                kandidat.getQuality(),
                kandidat.getTanggungJawab(),
                kandidat.getImprovment(),
                kandidat.getAbsensi(),
                kandidat.getPsikotes(),
                kandidat.getHasil()
            });
        }

        jTable1.setModel(model);
    }

    public void getKaryawanComboBox() {
        List<KaryawanModel> karyawanList = karyawanDao.findAll();

        jComboBox1.removeAllItems(); // Kosongkan comboBox dulu
        karyawanMap.clear(); // Bersihkan mapping sebelumnya

        if (karyawanList.isEmpty()) {
            System.out.println("Tidak ada data karyawan ditemukan.");
            return;
        }

        for (KaryawanModel karyawan : karyawanList) {
            String nama = karyawan.getName();
            Integer id = karyawan.getId();

            jComboBox1.addItem(nama); // Tambahkan nama ke comboBox
            karyawanMap.put(nama, id); // Simpan mapping nama -> id

            // Log tiap item yang dimasukkan
            System.out.println("Karyawan dimuat: " + nama + " (ID: " + id + ")");
        }

        System.out.println("Total karyawan dimuat ke comboBox: " + karyawanList.size());
    }

    public void populateComboBox(JComboBox<String> comboBox, List<String> items) {
        comboBox.removeAllItems();
        for (String item : items) {
            comboBox.addItem(item);
        }
    }
    /**
     * Creates new form PerhitunganSawView
     */
    public PerhitunganSawView() {
        initComponents();
        
        this.karyawanDao = new KaryawanDaoImpl();
        this.kandidatDao = new KandidatDaoImpl();
        
        getKaryawanComboBox();
        getAllData();
        
        List<String> label = Arrays.asList("Sangat Baik", "Cukup Baik", "Kurang Baik");
        
        populateComboBox(productivityComboBox, label);
        populateComboBox(qualityBox, label);        
        populateComboBox(tanggungJawabBox, label);
        populateComboBox(improvmentBox, label);
        populateComboBox(absensiBox, label);
        populateComboBox(psikotesBox, label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        productivityComboBox = new javax.swing.JComboBox<>();
        qualityBox = new javax.swing.JComboBox<>();
        tanggungJawabBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        improvmentBox = new javax.swing.JComboBox<>();
        absensiBox = new javax.swing.JComboBox<>();
        psikotesBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Pilih ID Karyawan ");

        jLabel3.setText("Productivity");

        jLabel4.setText("Quality");

        jLabel5.setText("Tanggung Jawab");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        productivityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tercapai", "Cukup Tercapai", "Tidak Tecapai" }));

        qualityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tanggungJawabBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Absensi");

        jLabel7.setText("Improvement");

        jLabel8.setText("Psikotes");

        improvmentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        absensiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        psikotesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Kinerja Terbaik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Semua Kinerja");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Data Karyawan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productivityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qualityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggungJawabBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(improvmentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(absensiBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psikotesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(improvmentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productivityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(absensiBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(qualityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(psikotesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tanggungJawabBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Data Perhitungan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Ambil nama karyawan dari combo box
        String selectedName = (String) jComboBox1.getSelectedItem();
        if (selectedName == null || !karyawanMap.containsKey(selectedName)) {
            JOptionPane.showMessageDialog(this, "Pilih nama karyawan terlebih dahulu.");
            System.out.println("Karyawan belum dipilih atau tidak ditemukan di map.");
            return;
        }

        int idKaryawan = karyawanMap.get(selectedName);
        System.out.println("ID Karyawan terpilih: " + idKaryawan);

        // Ambil nilai dari combo box (langsung sebagai String, misal "Baik", "Cukup")
        String productivity = (String) productivityComboBox.getSelectedItem();
        String quality = (String) qualityBox.getSelectedItem();
        String tanggungJawab = (String) tanggungJawabBox.getSelectedItem();
        String improvement = (String) improvmentBox.getSelectedItem();
        String absensi = (String) absensiBox.getSelectedItem();
        String psikotes = (String) psikotesBox.getSelectedItem();

        // Log nilai-nilainya
        System.out.println("Nilai input:");
        System.out.println("Productivity: " + productivity);
        System.out.println("Quality: " + quality);
        System.out.println("Tanggung Jawab: " + tanggungJawab);
        System.out.println("Improvement: " + improvement);
        System.out.println("Absensi: " + absensi);
        System.out.println("Psikotes: " + psikotes);

        // Set ke model kandidat
        KandidatModel kandidat = new KandidatModel();
        kandidat.setIdKaryawan(idKaryawan);
        kandidat.setProductivity(productivity);
        kandidat.setQuality(quality);
        kandidat.setTanggungJawab(tanggungJawab);
        kandidat.setImprovment(improvement);
        kandidat.setAbsensi(absensi);
        kandidat.setPsikotes(psikotes);

        // Simpan ke DB
        int result = kandidatDao.create(kandidat);
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Data kandidat berhasil disimpan.");
            System.out.println("Data kandidat berhasil disimpan ke database.");
            getAllData(); // Refresh tabel
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data kandidat.");
            System.out.println("Gagal menyimpan data kandidat.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String templateName = "KaryawanTerbaik.jrxml";
            InputStream reportStream = ReportView.class.getResourceAsStream("/resources/reports/" + templateName);

            if (reportStream == null) {
                throw new IllegalArgumentException("File report tidak ditemukan: " + templateName);
            }

            JasperDesign jd = JRXmlLoader.load(reportStream);
            JasperReport jr = JasperCompileManager.compileReport(jd);

            Connection dbConnection = DatabaseUtil.getInstance().getConnection();

            HashMap<String, Object> parameter = new HashMap<>();
            parameter.put("PATH", "src/resources/images/");

            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dbConnection);
            JasperViewer.viewReport(jp, false);

        } catch (JRException e) {
            System.err.println("Terjadi kesalahan saat memproses laporan JasperReports:");
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan:");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String templateName = "LaporanSemuaKinerja.jrxml";
            InputStream reportStream = ReportView.class.getResourceAsStream("/resources/reports/" + templateName);

            if (reportStream == null) {
                throw new IllegalArgumentException("File report tidak ditemukan: " + templateName);
            }

            JasperDesign jd = JRXmlLoader.load(reportStream);
            JasperReport jr = JasperCompileManager.compileReport(jd);

            Connection dbConnection = DatabaseUtil.getInstance().getConnection();

            HashMap<String, Object> parameter = new HashMap<>();
            parameter.put("PATH", "src/resources/images/");

            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dbConnection);
            JasperViewer.viewReport(jp, false);

        } catch (JRException e) {
            System.err.println("Terjadi kesalahan saat memproses laporan JasperReports:");
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan:");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         try {
            String templateName = "LaporanKaryawan.jrxml";
            InputStream reportStream = ReportView.class.getResourceAsStream("/resources/reports/" + templateName);

            if (reportStream == null) {
                throw new IllegalArgumentException("File report tidak ditemukan: " + templateName);
            }

            JasperDesign jd = JRXmlLoader.load(reportStream);
            JasperReport jr = JasperCompileManager.compileReport(jd);

            Connection dbConnection = DatabaseUtil.getInstance().getConnection();

            HashMap<String, Object> parameter = new HashMap<>();
            parameter.put("PATH", "src/resources/images/");

            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dbConnection);
            JasperViewer.viewReport(jp, false);

        } catch (JRException e) {
            System.err.println("Terjadi kesalahan saat memproses laporan JasperReports:");
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan:");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> absensiBox;
    private javax.swing.JComboBox<String> improvmentBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> productivityComboBox;
    private javax.swing.JComboBox<String> psikotesBox;
    private javax.swing.JComboBox<String> qualityBox;
    private javax.swing.JComboBox<String> tanggungJawabBox;
    // End of variables declaration//GEN-END:variables
}
